import { stringify } from "yaml";

interface ProviderMapping {
  langchainProvider: string;
  envVarMap: Record<string, string>;
  extraArgs?: Record<string, unknown>;
}

const PROVIDER_MAP: Record<string, ProviderMapping> = {
  openai: {
    langchainProvider: "ChatOpenAI",
    envVarMap: { OPENAI_API_KEY: "OPENAI_API_KEY" },
  },
  aws_bedrock: {
    langchainProvider: "ChatBedrock",
    envVarMap: {
      AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID",
      AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY",
      AWS_REGION: "AWS_DEFAULT_REGION",
    },
  },
  google: {
    langchainProvider: "ChatGoogleGenerativeAI",
    envVarMap: { GOOGLE_API_KEY: "GOOGLE_API_KEY" },
  },
  ollama: {
    langchainProvider: "ChatOllama",
    envVarMap: {},
  },
  azure: {
    langchainProvider: "AzureChatOpenAI",
    envVarMap: {
      AZURE_OPENAI_API_KEY: "AZURE_OPENAI_API_KEY",
      AZURE_OPENAI_ENDPOINT: "AZURE_OPENAI_ENDPOINT",
    },
  },
  groq: {
    langchainProvider: "ChatOpenAI",
    envVarMap: { GROQ_API_KEY: "OPENAI_API_KEY" },
    extraArgs: {
      configuration: { baseURL: "https://api.groq.com/openai/v1" },
    },
  },
};

/**
 * Generates provider-settings.yaml content from chat UI selections.
 * Maps UI provider IDs (e.g. "aws_bedrock") to LangChain provider names
 * (e.g. "ChatBedrock") and builds the YAML structure that parseModelConfig expects.
 */
export function generateProviderSettingsYaml(
  uiProviderId: string,
  model: string,
  credentials?: Record<string, string>,
): string {
  const mapping = PROVIDER_MAP[uiProviderId];
  if (!mapping) {
    throw new Error(`Unknown provider: ${uiProviderId}`);
  }

  const environment: Record<string, string> = {};
  if (credentials) {
    for (const [uiKey, yamlKey] of Object.entries(mapping.envVarMap)) {
      if (credentials[uiKey]) {
        environment[yamlKey] = credentials[uiKey];
      }
    }
  }

  const args: Record<string, unknown> = { model, ...mapping.extraArgs };

  const doc: Record<string, unknown> = {
    environment: {},
    active: {
      ...(Object.keys(environment).length > 0 ? { environment } : {}),
      provider: mapping.langchainProvider,
      args,
    },
  };

  return (
    "# Generated by Konveyor chat UI — edit via the settings gear in the chat panel\n---\n" +
    stringify(doc)
  );
}
