import { AnalyzerClient } from "./client/analyzerClient";
import { KonveyorGUIWebviewViewProvider } from "./KonveyorGUIWebviewViewProvider";
import * as vscode from "vscode";
import { AnalysisProfile, ExtensionData, ModifiedFileState } from "@editor-extensions/shared";
import { type InMemoryCacheWithRevisions, type KaiModelProvider } from "@editor-extensions/agentic";
import { Immutable } from "immer";
import { IssuesModel } from "./issueView";
import { DiagnosticTaskManager } from "./taskManager/taskManager";
import winston from "winston";
import { VerticalDiffManager } from "./diff/vertical/manager";
import { StaticDiffAdapter } from "./diff/staticDiffAdapter";
import { BatchedAnalysisTrigger } from "./analysis/batchedAnalysisTrigger";
import { HubConnectionManager } from "./hub";
import { type ExtensionStore } from "./store/extensionStore";
import { FeatureRegistry } from "./features/featureRegistry";

export interface ExtensionState {
  store: ExtensionStore;
  analyzerClient: AnalyzerClient;
  hubConnectionManager: HubConnectionManager;
  webviewProviders: Map<string, KonveyorGUIWebviewViewProvider>;
  extensionContext: vscode.ExtensionContext;
  diagnosticCollection: vscode.DiagnosticCollection;
  issueModel: IssuesModel;
  data: Immutable<ExtensionData>;
  mutate: (recipe: (draft: ExtensionData) => void) => void;
  profiles?: AnalysisProfile[];
  activeProfileId?: string;
  kaiFsCache: InMemoryCacheWithRevisions<string, string>;
  taskManager: DiagnosticTaskManager;
  modifiedFiles: Map<string, ModifiedFileState>;
  logger: winston.Logger;
  modelProvider: KaiModelProvider | undefined;
  modelProviderSource?: "hub-proxy" | "local-config";
  verticalDiffManager?: VerticalDiffManager;
  staticDiffAdapter?: StaticDiffAdapter;
  batchedAnalysisTrigger?: BatchedAnalysisTrigger;
  featureClients: Map<string, unknown>;
  featureRegistry?: FeatureRegistry;
}
