name: Nightly CI (repo level @main)

on:
  schedule:
    - cron: "35 5 * * *" # every day @ 5:35am UTC

  workflow_dispatch:

# https://typicode.github.io/husky/how-to.html#ci-server-and-docker
env:
  HUSKY: 0

jobs:
  nightly:
    uses: ./.github/workflows/ci-repo.yml
